In [5]:
import numpy as np

In [4]:
#assign input values

In [25]:
input_value = np.array([[0,0], [0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [26]:
#assign output values

In [27]:
output = np.array([0,1,1,0])
output = output.reshape(4,1)
output.shape

(4, 1)

In [28]:
#assign weights

In [29]:
weights = np.array([[0.1], [0.2]])
weights

array([[0.1],
       [0.2]])

In [30]:
#add bias

In [31]:
bias = 0.3

In [32]:
#activation function

In [33]:
def sigmoid_func(x):
    return 1/(1 + np.exp(-x))

In [34]:
#derivative of sigmoid function

In [35]:
def der(x):
    return sigmoid_func(x) * (1- sigmoid_func(x))

In [36]:
#updating weights

In [37]:
for epochs in range(10000):
    input_arr = input_value
    
    weighted_sum = np.dot(input_arr, weights) + bias
    first_output = sigmoid_func(weighted_sum)
    
    error = first_output - output
    total_error = np.square(np.subtract(first_output,output)).mean()
    #print(total_error)
    
    first_der = error
    second_der = der(first_output)
    derivative = first_der * second_der
    
    t_input = input_value.T
    final_derivative = np.dot(t_input, derivative)
    
    #update weights
    weights = weights - 0.05 * final_derivative
    
    #update bias
    for i in derivative:
        bias = bias - 0.05 * 1

print(weights)
print(bias)

C:\Users\Student\AppData\Local\Temp\ipykernel_12688\314844799.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-x))


[[124.96150963]
 [250.04776939]]
-1999.699999998729


In [38]:
# predictions

In [40]:
pred = np.array([1,0])
result = np.dot(pred, weights) + bias
res = sigmoid_func(result)
print(res)

[0.]


C:\Users\Student\AppData\Local\Temp\ipykernel_12688\314844799.py:2: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-x))
